Models/ErrorViewModel.cs
using System;

namespace SquareCalc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CalcController.cs
using Microsoft.AspNetCore.Mvc;

namespace SquareCalc.Controllers
{
    public class CalcController : Controller
    {
        public ActionResult Sqrt()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Sqrt(string firstnumber, string secondnumber)
        {
            try
            {
                double number1 = System.Math.Sqrt(int.Parse(firstnumber));
                double number2 = System.Math.Sqrt(int.Parse(secondnumber));
                if (number1 > number2)
                {
                    string result1 = ($"The number {firstnumber} with square root {number1} has a higher square root than the number {secondnumber} with square root {number2}");
                    ViewBag.Result = result1;
                }
                if (number2 > number1)
                {
                    string result2 = ($"The number {secondnumber} with square root {number2} has a higher square root than the number {firstnumber} with square root {number1}");
                    ViewBag.Result = result2;
                }
                if (number1 == number2)
                {
                    string result3 = ("Enter 2 different values Please");
                    ViewBag.Result = result3;
                }
                if (int.Parse(firstnumber) <= 0 || int.Parse(secondnumber) < 0)
                {
                    string result5 = ("Error: +ve values only");
                    ViewBag.Result = result5;
                }
            }
            catch (System.Exception)
            {
                string result4 = ("Error");
                ViewBag.Result = result4;
                throw;
            }
           
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SquareCalc.Models;

namespace SquareCalc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Calc/Sqrt.cshtml
@{
    ViewData["Title"] = "Root page";
}

<div class="text-center">
    <h1 class="display-4">The Root Difference Function</h1>
</div>
@{
    if (ViewBag.Result != null)
    {
        <div>
            <p>@ViewBag.Result</p>
        </div>
    }
}
<div>
    <form asp-controller="Calc" asp-action="Sqrt" method="POST">
        <input type="number" placeholder="First Number" name="firstnumber" required/>
        <input type="number" placeholder="Second Number" name="secondnumber" required/>
        <button type="submit">Submit</button>
    </form>    
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SquareCalc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SquareCalc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SquareCalc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>